//! Renders the schema tables as the Markdown reference
//! `docs/widget-schema-v1.md`. A test keeps the committed file identical.

use std::fmt::Write;

use crate::API_VERSION;
use crate::catalog::{
    CATALOG_DOMAIN, CATALOG_FIELDS, CATALOG_FILE, ENVELOPE_FIELDS, LISTING_FIELDS,
    PACKAGE_REF_FIELDS, PREVIEW_FIELDS, PRODUCTION_BASE_URL, SEED_DOMAIN, SEED_FIELDS, TAGS,
    TARGET_FIELDS,
};
use crate::compiled_view::{COMPONENT_FIELDS, NODE_KINDS, VIEW_FIELDS};
use crate::icons::{ICON_CRATE, ICONS, LUCIDE_VERSION};
use crate::ipc::{
    self, DRAW_COMMANDS, FAILURES, FRAME_KINDS, HEADER, HOST_MESSAGES, Message, PATCH_OPS,
    VM_MESSAGES,
};
use crate::limits;
use crate::manifest::{
    DIMENSION_FIELDS, MANIFEST_FIELDS, NAME_FIELDS, PERMISSION_FIELDS, SIZING_FIELDS, VM_FIELDS,
};
use crate::model::{Field, Limit, Status, Unit};
use crate::package::FILE_CLASSES;
use crate::permissions::{
    CAPABILITIES, NETWORK_RULE_FIELDS, PARAMETER_CONSTRAINTS, PERMISSIONS, SensitiveRule,
};
use crate::results::{SHAPES, Shape};
use crate::services::{Requirement, SERVICE_ERRORS, SERVICES, ServiceKind, Target, WRITE_INTENTS};
use crate::style::{DEFAULT_SIZES, PROPERTIES, SELECTORS, SHEET_RULES, SyntaxEntry, VALUE_SYNTAX};
use crate::tokens::TOKENS;
use crate::view::{
    COMMON_ATTRIBUTES, Content, ELEMENTS, EVENTS, EXPRESSION_SUMMARY, Focus, NAMED_KEYS,
    TEMPLATE_CONSTRUCTS,
};
use crate::wrapper::{CHOICE_FIELDS, LABEL_FIELDS, ROW_FIELDS, ROW_TYPES, WRAPPER_FIELDS};

pub const DOCUMENT_PATH: &str = "docs/widget-schema-v1.md";

pub fn markdown() -> String {
    let mut out = String::new();
    intro(&mut out);
    limits_section(&mut out);
    view_section(&mut out);
    style_section(&mut out);
    tokens_section(&mut out);
    icons_section(&mut out);
    manifest_section(&mut out);
    wrapper_section(&mut out);
    permissions_section(&mut out);
    services_section(&mut out);
    ipc_section(&mut out);
    package_section(&mut out);
    catalog_section(&mut out);
    // Sections append blank lines independently; keep at most one between blocks.
    while out.contains("\n\n\n") {
        out = out.replace("\n\n\n", "\n\n");
    }
    out
}

fn intro(out: &mut String) {
    let _ = write!(
        out,
        "# Widget schema v1 reference\n\n\
<!-- Generated by `cargo run -p overcrow-widget-schema --example reference`. Do not edit. -->\n\n\
This reference is generated from the `overcrow-widget-schema` crate, the single source of \
truth of widget API version {API_VERSION} (OverCrow design record ADR 0001, D8). The host, \
the creator CLI and the Studio compile the same tables; anything absent from them is \
rejected.\n\n\
**Status.** A *fixed* value is final for v1; the VM budgets come from the P0.3 measurements \
(ADR 0002), the parity bounds from the P0.4 text spike (ADR 0003), and the sandbox and IPC \
bounds from the P1.6 and P1.7 measurements. A *provisional* value is a conservative placeholder \
until the named lot delivers its evidence: the P2.4 pilots check the light colours; P1.3 and \
P1.8 exercise rendering and service bounds. Capabilities, services and \
write intents follow the P0.6 audit of the built-ins. A \
provisional value is enforced exactly like a fixed one until it is revised.\n\n\
Lengths are logical pixels at 100 % content scale. Text limits count UTF-8 bytes unless the unit \
says characters, which are Unicode scalar values.\n"
    );
}

fn status(status: Status) -> String {
    match status {
        Status::Fixed => "fixed".into(),
        Status::Provisional { lot } => format!("**provisional ({lot})**"),
    }
}

fn amount(limit: &Limit) -> String {
    const KIB: u64 = 1024;
    const MIB: u64 = 1024 * 1024;
    match limit.unit {
        Unit::Bytes if limit.value >= MIB && limit.value.is_multiple_of(MIB) => {
            format!("{} MiB", limit.value / MIB)
        }
        Unit::Bytes if limit.value >= KIB && limit.value.is_multiple_of(KIB) => {
            format!("{} KiB", limit.value / KIB)
        }
        Unit::Count => limit.value.to_string(),
        unit => format!("{} {}", limit.value, unit.as_str()),
    }
}

fn yes(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn fields_table(out: &mut String, fields: &[Field]) {
    if fields.is_empty() {
        out.push_str("No fields.\n\n");
        return;
    }
    out.push_str("| Field | Type | Required | Meaning |\n| --- | --- | --- | --- |\n");
    for field in fields {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            field.name,
            field.ty.describe(),
            yes(field.required),
            field.summary
        );
    }
    out.push('\n');
}

fn syntax_table(out: &mut String, heading: &str, entries: &[SyntaxEntry]) {
    let _ = write!(out, "| {heading} | Meaning |\n| --- | --- |\n");
    for entry in entries {
        let _ = writeln!(out, "| `{}` | {} |", entry.syntax, entry.summary);
    }
    out.push('\n');
}

fn limits_section(out: &mut String) {
    out.push_str(
        "\n## Limits\n\n| Limit | Value | Status | Meaning |\n| --- | --- | --- | --- |\n",
    );
    for limit in limits::ALL {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} |",
            limit.key,
            amount(limit),
            status(limit.status),
            limit.summary
        );
    }
}

fn view_section(out: &mut String) {
    out.push_str(
        "\n## View\n\n`view.ocml` is XML-like markup compiled ahead of time by the CLI: \
template expressions become code in `logic.js`, and the VM emits scene patches that the host \
validates against the elements below.\n\n### Template constructs\n\n\
| Syntax | Meaning |\n| --- | --- |\n",
    );
    for construct in TEMPLATE_CONSTRUCTS {
        let _ = writeln!(out, "| `{}` | {} |", construct.syntax, construct.summary);
    }
    let _ = write!(
        out,
        "\nExpressions: {EXPRESSION_SUMMARY}\n\n### Elements\n\n"
    );
    out.push_str(
        "| Element | Content | Parents | Focus | Role | Events | Meaning |\n\
| --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for element in ELEMENTS {
        let content = match element.content {
            Content::Empty => "empty".to_string(),
            Content::Text => "text".to_string(),
            Content::Inline => "inline: `span`, `icon`, `image`".to_string(),
            Content::Flow => "flow".to_string(),
            Content::Only(names) => code_list(names),
        };
        let parents = if element.parents.is_empty() {
            "any flow".to_string()
        } else {
            code_list(element.parents)
        };
        let focus = match element.focus {
            Focus::Never => "never",
            Focus::Always => "always",
            Focus::WhenSubscribed => "when subscribed",
        };
        let events = if element.events.is_empty() {
            "none".to_string()
        } else {
            code_list(element.events)
        };
        let _ = writeln!(
            out,
            "| `{}` | {content} | {parents} | {focus} | {} | {events} | {} |",
            element.name, element.role, element.summary
        );
    }
    out.push_str("\n#### Attributes of every element\n\n");
    fields_table(out, COMMON_ATTRIBUTES);
    for element in ELEMENTS
        .iter()
        .filter(|element| !element.attributes.is_empty())
    {
        let _ = write!(out, "#### `{}` attributes\n\n", element.name);
        fields_table(out, element.attributes);
    }
    out.push_str(
        "### Events\n\nA gesture event authorizes gesture-bound service calls made while the VM \
handles it, in Interactive mode only.\n\n\
| Event | Gesture | Detail | Meaning |\n| --- | --- | --- | --- |\n",
    );
    for event in EVENTS {
        let detail = if event.detail.is_empty() {
            "none".to_string()
        } else {
            code_list(
                &event
                    .detail
                    .iter()
                    .map(|field| field.name)
                    .collect::<Vec<_>>(),
            )
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | {detail} | {} |",
            event.name,
            yes(event.gesture),
            event.summary
        );
    }
    let _ = write!(
        out,
        "\nNamed `keydown` keys: {}. Any other `key` is one printable grapheme.\n",
        code_list(NAMED_KEYS)
    );
}

fn style_section(out: &mut String) {
    out.push_str("\n## Style\n\n### Properties\n\n");
    out.push_str(
        "Animatable properties change paint only, so transitions and animations never rerun \
layout. `text-overflow: marquee` scrolls one overflowing line back and forth at a host-defined \
speed, pausing at each end; it runs only while the widget is visible, counts as an active \
animation and restarts when the text changes.\n\n| Property | Group | Value | Initial | Inherited | Animatable |\n\
| --- | --- | --- | --- | --- | --- |\n",
    );
    for property in PROPERTIES {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | `{}` | {} | {} |",
            property.name,
            property.group,
            property.value.syntax(),
            property.initial,
            yes(property.inherited),
            yes(property.animatable)
        );
    }
    out.push_str("\n### Selectors\n\n");
    syntax_table(out, "Selector", SELECTORS);
    out.push_str("### Values\n\n");
    syntax_table(out, "Syntax", VALUE_SYNTAX);
    out.push_str("### Sheet rules\n\n");
    syntax_table(out, "Rule", SHEET_RULES);
    out.push_str(
        "### Default sizes\n\nHost-drawn leaves take these sizes, in logical px at 100 %, \
unless `width` or `height` is set. A row with a condition applies when the attribute has that \
value; any other element, `canvas` included, is sized by style only.\n\n\
| Element | When | Width | Height | Status |\n| --- | --- | --- | --- | --- |\n",
    );
    for row in DEFAULT_SIZES {
        let when = row.when.map_or("—".to_owned(), |(name, value)| {
            format!("`{name}=\"{value}\"`")
        });
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            row.element,
            when,
            row.width.describe(),
            row.height.describe(),
            status(row.status)
        );
    }
}

fn tokens_section(out: &mut String) {
    out.push_str(
        "## Design tokens\n\nDark values are the current overlay palette. The built-ins have no \
light theme yet, so no capture can check the light colours: apart from the fixed \
`--color-on-accent`, they remain a proposal.\n\n\
| Token | Type | Dark | Light | Status | Meaning |\n| --- | --- | --- | --- | --- | --- |\n",
    );
    for token in TOKENS {
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` | `{}` | {} | {} |",
            token.name,
            token.ty.as_str(),
            token.dark,
            token.light,
            status(token.status),
            token.summary
        );
    }
}

fn icons_section(out: &mut String) {
    let _ = write!(
        out,
        "\n## Icons\n\nEvery icon of the pinned `{ICON_CRATE}` crate (Lucide {LUCIDE_VERSION}, \
{} names) is valid in `icon` elements and `wrapper.menu` rows; any other name is rejected. The \
crate is the host's only icon source. The exact list is \
[`icons_generated.rs`](../crates/overcrow-widget-schema/src/icons_generated.rs), regenerated \
from the crate's name table by `scripts/generate-widget-icons.py`. Within API v1 the set may \
grow but never loses or renames a name.\n",
        ICONS.len()
    );
}

fn manifest_section(out: &mut String) {
    out.push_str(
        "\n## Manifest\n\n`manifest.json` is one strict JSON object: a byte-order mark, a \
duplicate key, trailing data or an unknown field rejects it, and so does any Web API manifest. \
The format of the package that carries it is in [Package](#package) and \
[`widget-package-v1.md`](widget-package-v1.md).\n\n### `manifest.json`\n\n",
    );
    fields_table(out, MANIFEST_FIELDS);
    out.push_str(
        "### `WidgetName`\n\nEach text is non-empty, trimmed, without control characters and at \
most `MAX_WIDGET_NAME_CHARS` characters.\n\n",
    );
    fields_table(out, NAME_FIELDS);
    out.push_str("### `Sizing`\n\n`min` ≤ `preferred` ≤ `max` on both axes.\n\n");
    fields_table(out, SIZING_FIELDS);
    out.push_str("### `Dimensions`\n\n");
    fields_table(out, DIMENSION_FIELDS);
    out.push_str(
        "### `VmRequest`\n\nA widget that needs more than the default heap requests it here; \
nothing else about the VM budgets can be changed by a manifest.\n\n",
    );
    fields_table(out, VM_FIELDS);
    out.push_str(
        "### `Permissions`\n\nKeys are the permissions of [Permissions](#permissions); a \
sensitive capability rejects `network` rules and `clipboardWrite: true`.\n\n",
    );
    fields_table(out, PERMISSION_FIELDS);
}

fn package_section(out: &mut String) {
    out.push_str(
        "\n## Package\n\nA `.ocpkg` v1 archive is a stored (uncompressed) zip in one pinned \
layout, so identical files give identical bytes and the archive digest identifies the \
content. [`widget-package-v1.md`](widget-package-v1.md) specifies the layout, the ledger, \
admission and the catalog flow.\n\n### Files\n\nAny other entry rejects the package.\n\n\
| Path | Required | Limit | Meaning |\n| --- | --- | --- | --- |\n",
    );
    for class in FILE_CLASSES {
        let _ = writeln!(
            out,
            "| `{}` | {} | `{}` | {} |",
            class.path,
            yes(class.required),
            class.limit.key,
            class.summary
        );
    }
    out.push_str(
        "\n### Compiled view `view.json`\n\nThe CLI compiles `view.ocml` into this tree and \
every template expression and handler into a function of `logic.js`; the tree refers to them \
by index. The host validates it at activation and sends it to the VM in `Init`.\n\n",
    );
    fields_table(out, VIEW_FIELDS);
    out.push_str("#### `Component`\n\n");
    fields_table(out, COMPONENT_FIELDS);
    out.push_str(
        "#### Nodes\n\nA node is an object recognised by one discriminating key. Scope names \
are `[A-Za-z_][A-Za-z0-9_]*` within `MAX_IDENTIFIER_BYTES`; expression indices are below \
`expressions`.\n",
    );
    for kind in NODE_KINDS {
        let _ = write!(out, "\n##### `{}`\n\n{}\n\n", kind.key, kind.summary);
        fields_table(out, kind.fields);
    }
}

fn catalog_section(out: &mut String) {
    let _ = write!(
        out,
        "\n## Catalog\n\nThe v1 catalog is `{PRODUCTION_BASE_URL}{CATALOG_FILE}`. Its envelope \
carries an Ed25519 signature of the domain string `{}` followed by the payload bytes; the \
offline seed uses `{}`. `\\0` is one NUL byte.\n\n### Envelope\n\n",
        String::from_utf8_lossy(CATALOG_DOMAIN).replace('\0', "\\0"),
        String::from_utf8_lossy(SEED_DOMAIN).replace('\0', "\\0"),
    );
    fields_table(out, ENVELOPE_FIELDS);
    out.push_str("### Catalog payload\n\n");
    fields_table(out, CATALOG_FIELDS);
    out.push_str("### Seed payload\n\n");
    fields_table(out, SEED_FIELDS);
    out.push_str("### `Target`\n\n");
    fields_table(out, TARGET_FIELDS);
    out.push_str("### `PackageRef`\n\n");
    fields_table(out, PACKAGE_REF_FIELDS);
    out.push_str("### `Listing`\n\n");
    fields_table(out, LISTING_FIELDS);
    out.push_str("### `Preview`\n\n");
    fields_table(out, PREVIEW_FIELDS);
    out.push_str("### Tags\n\n| Tag | Meaning |\n| --- | --- |\n");
    for tag in TAGS {
        let _ = writeln!(out, "| `{}` | {} |", tag.name, tag.summary);
    }
}

fn wrapper_section(out: &mut String) {
    out.push_str(
        "\n## Wrapper menu\n\nThe manifest `wrapper` object extends the host options menu \
(ADR 0001, D12). Host rows (opacity, scale, fit to content, passive visibility) come first, \
are separated and are not declared here. Widget rows only set a declared value or emit a \
declared event: they cannot change a grant, open a URL or act as the gesture of a write \
intent. Values are stored by the host profile store and reach the VM in `Init` and `Snapshot` \
after durable acknowledgement.\n\n### `wrapper`\n\n",
    );
    fields_table(out, WRAPPER_FIELDS);
    out.push_str("### Fields of every row\n\n");
    fields_table(out, ROW_FIELDS);
    out.push_str("### Row types\n\n");
    for row in ROW_TYPES {
        let _ = write!(out, "#### `{}`\n\n{}\n\n", row.name, row.summary);
        if !row.fields.is_empty() {
            fields_table(out, row.fields);
        }
    }
    out.push_str(
        "### `MenuLabel`\n\nEach text is non-empty, trimmed, without control characters and at \
most `MAX_MENU_LABEL_CHARS` characters.\n\n",
    );
    fields_table(out, LABEL_FIELDS);
    out.push_str("### `MenuChoice`\n\n");
    fields_table(out, CHOICE_FIELDS);
}

fn permissions_section(out: &mut String) {
    out.push_str(
        "## Permissions\n\nDeclaring a permission or capability grants nothing: activation \
requires consent recorded by the host.\n\n\
| Permission | With a sensitive capability | Meaning |\n| --- | --- | --- |\n",
    );
    for permission in PERMISSIONS {
        let rule = match permission.with_sensitive {
            SensitiveRule::Allowed => "allowed",
            SensitiveRule::Forbidden => "manifest rejected",
            SensitiveRule::ProcessLifetime => "process-lifetime data only",
        };
        let _ = writeln!(
            out,
            "| `{}` | {rule} | {} |",
            permission.name, permission.summary
        );
    }
    out.push_str("\n### Network rules\n\n");
    fields_table(out, NETWORK_RULE_FIELDS);
    out.push_str(
        "### `ParameterConstraint` types\n\n| Type | Shape | Accepts |\n| --- | --- | --- |\n",
    );
    for constraint in PARAMETER_CONSTRAINTS {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            constraint.name,
            constraint.ty.describe(),
            constraint.summary
        );
    }
    out.push_str(
        "\n### Capabilities\n\n| Capability | Sensitive | Account | Status | Meaning |\n\
| --- | --- | --- | --- | --- |\n",
    );
    for capability in CAPABILITIES {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            capability.name,
            yes(capability.sensitive),
            capability.account.unwrap_or("none"),
            status(capability.status),
            capability.summary
        );
    }
}

/// Member tables of a record shape, nested records and alternatives
/// flattened with a dotted prefix.
fn shape_members(out: &mut String, shape: &Shape, prefix: &str) {
    match shape {
        Shape::Record(members) => {
            if prefix.is_empty() {
                out.push_str("| Member | Shape | Meaning |\n| --- | --- | --- |\n");
            }
            for member in *members {
                let name = format!("{prefix}{}", member.name);
                let _ = writeln!(
                    out,
                    "| `{name}` | {} | {} |",
                    member.shape.describe(),
                    member.summary
                );
                let inner = match member.shape {
                    Shape::Nullable(inner) => *inner,
                    other => other,
                };
                if let Shape::Record(_) = inner {
                    shape_members(out, &inner, &format!("{name}."));
                }
            }
            if prefix.is_empty() {
                out.push('\n');
            }
        }
        Shape::OneOf(shapes) => {
            for shape in *shapes {
                shape_members(out, shape, prefix);
            }
        }
        _ => {}
    }
}

fn services_section(out: &mut String) {
    out.push_str(
        "\n## Services\n\nAuthority is checked by the host at every call, immediately before \
acting. Gesture services also require the `cause` of a gesture event of the current Interactive \
epoch.\n\n| Service | Requires | Kind | Gesture | Confirmation | Parameters | Result | Shape | Status |\n\
| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for service in SERVICES {
        let requires = match service.requires {
            Requirement::None => "nothing".to_string(),
            Requirement::Permission(name) => format!("permission `{name}`"),
            Requirement::Capability(name) => format!("capability `{name}`"),
        };
        let kind = match service.kind {
            ServiceKind::Call => "call",
            ServiceKind::Subscribe => "subscribe",
        };
        let params = if service.params.is_empty() {
            "none".to_string()
        } else {
            service
                .params
                .iter()
                .map(|field| {
                    let optional = if field.required { "" } else { "?" };
                    format!("`{}{optional}`: {}", field.name, field.ty.describe())
                })
                .collect::<Vec<_>>()
                .join("; ")
        };
        let _ = writeln!(
            out,
            "| `{}` | {requires} | {kind} | {} | {} | {params} | {} | {} | {} |",
            service.name,
            yes(service.gesture),
            yes(service.confirm),
            service.result,
            service.returns.describe(),
            status(service.status)
        );
    }
    out.push_str(
        "\n### Result shapes\n\nThe shape of each result and subscription update, and of \
`ServiceError`. Records are exact: every member is present, a nullable one as `null`, and no \
other key is. Integers stay below 2^53.\n\n",
    );
    for named in SHAPES {
        let _ = write!(
            out,
            "#### `{}`\n\n{} {}\n\n",
            named.name,
            named.summary,
            named.shape.describe()
        );
        shape_members(out, &named.shape, "");
    }
    let _ = write!(
        out,
        "\nService error codes: {}.\n\n### Write intents\n\n\
A `form` with an `intent` sends the values of its named host-owned controls straight to the \
service when the user submits it; the VM receives a `submit` event with the outcome but never \
supplies the body. Named controls not listed are rejected.\n\n",
        code_list(SERVICE_ERRORS)
    );
    for intent in WRITE_INTENTS {
        let target = match intent.target {
            Target::Refused => "refused".to_string(),
            Target::Optional(meaning) => format!("optional ({meaning})"),
            Target::Required(meaning) => format!("required ({meaning})"),
        };
        let _ = write!(
            out,
            "#### `{}`\n\nCapability `{}`; `target` attribute {target}. Status: {}.\n\n",
            intent.name,
            intent.capability,
            status(intent.status)
        );
        fields_table(out, intent.fields);
    }
}

fn ipc_section(out: &mut String) {
    let _ = write!(
        out,
        "## IPC\n\nOCWV v1 runs over one inherited pipe or socket pair per widget; the VM never \
opens or names an endpoint. Each frame is a {}-byte big-endian header, a bounded JSON control \
part and an optional raw payload.\n\n| Offset | Bytes | Field | Rule |\n| --- | --- | --- | --- |\n",
        ipc::HEADER_BYTES
    );
    for field in HEADER {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            field.offset, field.bytes, field.name, field.rule
        );
    }
    out.push_str("\n### Frame kinds\n\n| Code | Name | Direction | Raw payload | Meaning |\n| --- | --- | --- | --- | --- |\n");
    for kind in FRAME_KINDS {
        let raw = kind
            .raw
            .map_or("none".to_string(), |limit| format!("≤ `{}`", limit.key));
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {raw} | {} |",
            kind.code,
            kind.name,
            kind.direction.as_str(),
            kind.summary
        );
    }
    let _ = write!(
        out,
        "\nRaw payload encoding ({}): {}\n",
        status(ipc::PAYLOAD_ENCODING_STATUS),
        ipc::PAYLOAD_ENCODING
    );
    out.push_str(
        "\n### VM process arguments\n\nThe host starts the VM binary with exactly these \
arguments; anything else stops the VM before it reads a frame.\n\n",
    );
    fields_table(out, ipc::VM_ARGUMENTS);
    messages(out, "Host → VM messages", HOST_MESSAGES);
    messages(out, "VM → host messages", VM_MESSAGES);
    out.push_str(
        "\n### Headless test runtime\n\nThe creator test runtime (`overcrow-widget test`) runs \
the VM on virtual time. It adds this argument and this message, which a production runtime \
never accepts: its VM is built without them and stops on either.\n\n",
    );
    fields_table(out, ipc::HEADLESS_VM_ARGUMENTS);
    for message in ipc::HEADLESS_HOST_MESSAGES {
        let _ = write!(
            out,
            "#### `{}` (frame {})\n\n{}\n\n",
            message.name, message.frame, message.summary
        );
        fields_table(out, message.fields);
    }
    messages(out, "Scene patch operations", PATCH_OPS);
    out.push_str(
        "\nIn `create` and `setAttrs`, `on` is a JSON array of event names of the element, \
sorted in byte order without duplicates, and `class` is one string of distinct classes separated \
by one space, as in the view. Node-reference attributes and `Draw.canvas` carry a `ref` name \
declared by the view; operations keep node IDs.\n",
    );
    out.push_str(
        "\n### Draw commands\n\nEach command is `[name, …arguments]` in order.\n\n\
| Command | Arguments | Meaning |\n| --- | --- | --- |\n",
    );
    for command in DRAW_COMMANDS {
        let arguments = if command.fields.is_empty() {
            "none".to_string()
        } else {
            command
                .fields
                .iter()
                .map(|field| format!("`{}`: {}", field.name, field.ty.describe()))
                .collect::<Vec<_>>()
                .join("; ")
        };
        let _ = writeln!(
            out,
            "| `{}` | {arguments} | {} |",
            command.name, command.summary
        );
    }
    out.push_str("\n### Fault categories\n\n| Category | Fatal | Meaning |\n| --- | --- | --- |\n");
    for category in ipc::FAULT_CATEGORIES {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            category.name,
            yes(category.fatal),
            category.summary
        );
    }
    out.push_str(
        "\n### Failure categories\n\n| Category | Restarts | Meaning |\n| --- | --- | --- |\n",
    );
    for failure in FAILURES {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            failure.name,
            yes(failure.restarts),
            failure.summary
        );
    }
    out.push_str(
        "\nTransient failures restart after 1, 5 and 15 seconds, at most three times; the \
budget resets after 60 seconds of stable run.\n",
    );
}

fn messages(out: &mut String, heading: &str, messages: &[Message]) {
    let _ = write!(out, "\n### {heading}\n");
    for message in messages {
        let _ = write!(
            out,
            "\n#### `{}` (frame {})\n\n{}\n\n",
            message.name, message.frame, message.summary
        );
        fields_table(out, message.fields);
    }
}

fn code_list(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("`{name}`"))
        .collect::<Vec<_>>()
        .join(", ")
}
