//! Renders the schema tables as the TypeScript sources of `@overcrow/sdk`
//! (ADR 0001, D8): service parameters and results, capabilities, error
//! codes, limits, events, draw commands, tokens, icons and menu types. The
//! output is committed under `sdk/src/generated/`; a test keeps it identical.
//!
//! Only `limits.ts` and the service namespaces hold values: everything else
//! is a type, so the large unions (icons, draw commands, tokens) leave
//! nothing in `logic.js`.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::icons::{ICON_CRATE, ICONS};
use crate::ipc::{DRAW_COMMANDS, HOST_MESSAGES};
use crate::limits;
use crate::model::{Field, ValueType};
use crate::permissions::{CAPABILITIES, PERMISSIONS};
use crate::results::{SHAPES, Shape};
use crate::services::{Requirement, SERVICE_ERRORS, SERVICES, Service, ServiceKind};
use crate::tokens::{TOKENS, TokenType};
use crate::view::{EVENTS, NAMED_KEYS};
use crate::wrapper::{HOST_FEATURES, ROW_FIELDS};

/// Directory of the generated sources, relative to the repository root.
pub const OUTPUT_DIR: &str = "sdk/src/generated";

/// Services reached through dedicated SDK modules rather than a generated
/// namespace: timers, subscription cancellation and `http.fetch`.
const HAND_WRITTEN: &[&str] = &["timer", "subscription", "http"];

const HEADER: &str = "// @generated by `cargo run -p overcrow-widget-schema --example sdk-types`.\n\
// Do not edit: change the schema in crates/overcrow-widget-schema and regenerate.\n";

/// `(file name, content)` of every generated source.
pub fn files() -> Vec<(&'static str, String)> {
    vec![
        ("schema.ts", schema()),
        ("icons.ts", icons()),
        ("limits.ts", limits()),
        ("services.ts", services()),
    ]
}

fn schema() -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "\nimport type { IconName } from \"./icons.js\";\n\n\
/** Any JSON value. */\n\
export type JsonValue =\n  | null\n  | boolean\n  | number\n  | string\n  | readonly JsonValue[]\n  | { readonly [key: string]: JsonValue };\n\n\
/** An image handle issued by a host service (`asset:<16 hex>`). */\n\
export type AssetHandle = `asset:${string}`;\n\n\
/** An image of the package (`assets/…`) or a host-issued handle. */\n\
export type ImageSource = `assets/${string}` | AssetHandle;\n",
    );
    host_types(&mut out);
    capabilities(&mut out);
    tokens(&mut out);
    events(&mut out);
    draw(&mut out);
    menu(&mut out);
    shapes(&mut out);
    service_maps(&mut out);
    out
}

fn icons() -> String {
    let mut out = String::from(HEADER);
    let _ = write!(
        out,
        "\n/** Name of a Lucide icon drawn by the host ({ICON_CRATE}, {} icons). */\nexport type IconName =\n",
        ICONS.len()
    );
    for name in ICONS.iter() {
        let _ = writeln!(out, "  | {}", quote(name));
    }
    finish(&mut out);
    out
}

fn host_types(out: &mut String) {
    out.push_str("\n// Host data.\n");
    let init = message("Init");
    for (alias, name, summary) in [
        ("Locale", "locale", "Interface language of the host."),
        ("Theme", "theme", "Colour theme of the host."),
        (
            "Mode",
            "mode",
            "Overlay mode: `interactive` receives input.",
        ),
    ] {
        let _ = writeln!(
            out,
            "\n/** {summary} */\nexport type {alias} = {};",
            keywords(field(init, name))
        );
    }
    let region = message("Region");
    out.push_str("\n/** Regional formats and time zone of the user (`host.region`). */\nexport interface Region {\n");
    for field in region.iter() {
        doc(out, "  ", field.summary);
        let _ = writeln!(
            out,
            "  readonly {}{}: {};",
            field.name,
            if field.required { "" } else { "?" },
            value_type(&field.ty)
        );
    }
    out.push_str("}\n");
    for (alias, name) in [("NumberFormat", "numberFormat"), ("DateOrder", "dateOrder")] {
        let _ = writeln!(
            out,
            "\n/** `Region.{name}`. */\nexport type {alias} = Region[{}];",
            quote(name)
        );
    }
}

fn capabilities(out: &mut String) {
    out.push_str("\n// Permissions and capabilities.\n\n/** A manifest permission. */\nexport type Permission =\n");
    for permission in PERMISSIONS {
        let _ = writeln!(out, "  | {}", quote(permission.name));
    }
    finish(out);
    out.push_str("\n/** A capability; declaring one grants nothing until the user consents. */\nexport type Capability =\n");
    for capability in CAPABILITIES {
        let _ = writeln!(out, "  | {}", quote(capability.name));
    }
    finish(out);
    out.push_str(
        "\n/** Capabilities that reveal user data: a widget declaring one gets no `network` or `clipboardWrite`, and only process-lifetime storage. */\nexport type SensitiveCapability =\n",
    );
    for capability in CAPABILITIES
        .iter()
        .filter(|capability| capability.sensitive)
    {
        let _ = writeln!(out, "  | {}", quote(capability.name));
    }
    finish(out);
    let mut by_capability: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut by_permission: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for service in SERVICES {
        match service.requires {
            Requirement::Capability(name) => {
                by_capability.entry(name).or_default().push(service.name)
            }
            Requirement::Permission(name) => {
                by_permission.entry(name).or_default().push(service.name)
            }
            Requirement::None => {}
        }
    }
    out.push_str("\n/** The services each capability authorizes. */\nexport interface CapabilityServices {\n");
    for capability in CAPABILITIES {
        let names = by_capability
            .get(capability.name)
            .map_or("never".to_owned(), |names| {
                names
                    .iter()
                    .map(|name| quote(name))
                    .collect::<Vec<_>>()
                    .join(" | ")
            });
        doc(out, "  ", capability.summary);
        let _ = writeln!(out, "  readonly {}: {names};", quote(capability.name));
    }
    out.push_str("}\n\n/** The services each permission authorizes. */\nexport interface PermissionServices {\n");
    for permission in PERMISSIONS {
        let names = by_permission
            .get(permission.name)
            .map_or("never".to_owned(), |names| {
                names
                    .iter()
                    .map(|name| quote(name))
                    .collect::<Vec<_>>()
                    .join(" | ")
            });
        doc(out, "  ", permission.summary);
        let _ = writeln!(out, "  readonly {}: {names};", quote(permission.name));
    }
    out.push_str("}\n");
}

fn tokens(out: &mut String) {
    out.push_str("\n// Design tokens.\n");
    for (alias, ty, summary) in [
        ("ColorToken", TokenType::Color, "A colour token."),
        ("LengthToken", TokenType::Length, "A length token."),
        ("FontSizeToken", TokenType::FontSize, "A font size token."),
        (
            "FontFamilyToken",
            TokenType::FontFamily,
            "A font family token.",
        ),
        ("TimeToken", TokenType::Time, "A duration token."),
        (
            "ShadowToken",
            TokenType::Shadow,
            "A shadow token, only as the whole `box-shadow` value.",
        ),
    ] {
        let _ = writeln!(out, "\n/** {summary} */\nexport type {alias} =");
        for token in TOKENS.iter().filter(|token| token.ty == ty) {
            let _ = writeln!(out, "  | {}", quote(token.name));
        }
        finish(out);
    }
    out.push_str(
        "\n/** Any design token, used as `var(--name)` in `style.ocss`. */\n\
export type TokenName = ColorToken | LengthToken | FontSizeToken | FontFamilyToken | TimeToken | ShadowToken;\n\n\
/** A draw colour: `#rgb`, `#rgba`, `#rrggbb`, `#rrggbbaa`, `rgb(r g b)`, `rgb(r g b / a)`, `transparent`, `currentColor` or a colour token. */\n\
export type Color =\n  | `#${string}`\n  | `rgb(${string})`\n  | \"transparent\"\n  | \"currentColor\"\n  | `var(${ColorToken})`;\n",
    );
}

fn events(out: &mut String) {
    out.push_str("\n// View events.\n\n/** An event a view node can forward (`on:<event>`). */\nexport type EventName =\n");
    for event in EVENTS {
        let _ = writeln!(out, "  | {}", quote(event.name));
    }
    finish(out);
    out.push_str("\n/** Events that are user gestures: gesture-bound services accept a call made while one is handled. */\nexport type GestureEventName =\n");
    for event in EVENTS.iter().filter(|event| event.gesture) {
        let _ = writeln!(out, "  | {}", quote(event.name));
    }
    finish(out);
    out.push_str("\n/** Named `keydown` keys; any other key is one printable grapheme. */\nexport type NamedKey =\n");
    for key in NAMED_KEYS {
        let _ = writeln!(out, "  | {}", quote(key));
    }
    finish(out);
    out.push_str("\n/** The `detail` of each event. */\nexport interface EventDetailMap {\n");
    for event in EVENTS {
        doc(out, "  ", event.summary);
        let _ = write!(out, "  readonly {}: ", event.name);
        record(out, "  ", event.detail);
        out.push_str(";\n");
    }
    out.push_str("}\n");
}

fn draw(out: &mut String) {
    out.push_str("\n// Canvas drawing.\n\n/** One vector command of a canvas draw list: its name, then its arguments in order. */\nexport type DrawCommand =\n");
    for command in DRAW_COMMANDS {
        let arguments: Vec<String> = command
            .fields
            .iter()
            .map(|field| format!(", {}: {}", field.name, value_type(&field.ty)))
            .collect();
        let _ = writeln!(
            out,
            "  | readonly [command: {}{}]",
            quote(command.name),
            arguments.concat()
        );
    }
    finish(out);
    out.push_str(
        "\n/** Name of a draw command. */\nexport type DrawCommandName = DrawCommand[0];\n",
    );
}

fn menu(out: &mut String) {
    let row_type = ROW_FIELDS
        .iter()
        .find(|field| field.name == "type")
        .map(|field| keywords(field.keywords()))
        .unwrap_or_default();
    let _ = write!(
        out,
        "\n// Options menu.\n\n/** Type of a `wrapper.menu` row. */\nexport type MenuRowType = {row_type};\n\n\
/** A host data source a menu row can require (`requires`). */\nexport type HostFeature = {};\n",
        keywords(HOST_FEATURES)
    );
}

fn shapes(out: &mut String) {
    out.push_str("\n// Service result shapes.\n\n/** Code of a failed service call or subscription. */\nexport type ServiceErrorCode =\n");
    for code in SERVICE_ERRORS {
        let _ = writeln!(out, "  | {}", quote(code));
    }
    finish(out);
    for named in SHAPES {
        out.push('\n');
        doc(out, "", named.summary);
        match named.shape {
            Shape::Record(_) => {
                let _ = write!(out, "export interface {} ", ts_name(named.name));
                shape(out, "", &named.shape);
                out.push('\n');
            }
            _ => {
                let _ = write!(out, "export type {} = ", ts_name(named.name));
                shape(out, "", &named.shape);
                out.push_str(";\n");
            }
        }
    }
}

fn service_maps(out: &mut String) {
    out.push_str("\n// Services.\n\n/** Every service name. */\nexport type ServiceName = keyof ServiceParamsMap;\n\n/** The parameters of each service. */\nexport interface ServiceParamsMap {\n");
    for service in SERVICES {
        doc(out, "  ", &format!("Parameters of `{}`.", service.name));
        let _ = write!(out, "  readonly {}: ", quote(service.name));
        if service.params.is_empty() {
            out.push_str("Record<string, never>");
        } else {
            record(out, "  ", service.params);
        }
        out.push_str(";\n");
    }
    out.push_str("}\n\n/** The result of each call, and each update of each subscription. */\nexport interface ServiceResultMap {\n");
    for service in SERVICES {
        doc(
            out,
            "  ",
            &format!("`{}`: {}.", service.name, service.result),
        );
        let _ = write!(out, "  readonly {}: ", quote(service.name));
        shape(out, "  ", &service.returns);
        out.push_str(";\n");
    }
    out.push_str("}\n\n/** Services answered once. */\nexport type CallServiceName =\n");
    for service in SERVICES
        .iter()
        .filter(|service| service.kind == ServiceKind::Call)
    {
        let _ = writeln!(out, "  | {}", quote(service.name));
    }
    finish(out);
    out.push_str("\n/** Services that send updates until cancelled. */\nexport type SubscribeServiceName =\n");
    for service in SERVICES
        .iter()
        .filter(|service| service.kind == ServiceKind::Subscribe)
    {
        let _ = writeln!(out, "  | {}", quote(service.name));
    }
    finish(out);
    out.push_str("\n/** Services accepted only while a gesture event is handled. */\nexport type GestureServiceName =\n");
    for service in SERVICES.iter().filter(|service| service.gesture) {
        let _ = writeln!(out, "  | {}", quote(service.name));
    }
    finish(out);
}

/// The limits a widget author works against: service parameters and
/// results, drawing, text, the view and the VM budgets. The others (frames,
/// packages, catalogs) stay in the schema reference.
pub const AUTHOR_LIMITS: &[&str] = &[
    "MAX_TIMERS",
    "MIN_TIMER_INTERVAL_MS",
    "MAX_SERVICE_CALLS_IN_FLIGHT",
    "MAX_SUBSCRIPTIONS",
    "MAX_STORAGE_KEYS",
    "MAX_STORAGE_KEY_BYTES",
    "MAX_STORAGE_VALUE_BYTES",
    "STORAGE_QUOTA_BYTES",
    "MAX_REQUEST_URL_BYTES",
    "MAX_HTTP_REQUEST_BYTES",
    "MAX_HTTP_RESPONSE_BYTES",
    "MAX_CLIPBOARD_BYTES",
    "MAX_OBJECT_ID_BYTES",
    "MAX_NOTES",
    "MAX_NOTE_ITEMS",
    "MAX_NOTE_TITLE_BYTES",
    "MAX_NOTE_BODY_BYTES",
    "MAX_NOTE_ITEM_BYTES",
    "MAX_REVIEW_CHARS",
    "MAX_CHAT_CHANNEL_BYTES",
    "MAX_CHAT_MESSAGE_CHARS",
    "MAX_CHAT_FRAGMENTS",
    "MAX_CHAT_FAVORITES",
    "MAX_DRAW_COMMANDS",
    "MAX_DRAW_STATE_DEPTH",
    "MAX_PATH_POINTS",
    "MAX_PATCH_BYTES",
    "MAX_SCENE_NODES",
    "MAX_CHILDREN",
    "MAX_NODE_TEXT_BYTES",
    "MAX_ATTRIBUTE_TEXT_BYTES",
    "MAX_LABEL_BYTES",
    "MAX_FIELD_TEXT_BYTES",
    "MAX_LOCALE_ENTRIES",
    "MAX_LOG_BYTES",
    "VM_HEAP_BYTES",
    "VM_MAX_HEAP_BYTES",
    "VM_TURN_BUDGET_MS",
    "VM_JOBS_PER_TURN",
    "VM_MESSAGES_PER_TURN",
];

/// The limits a widget works against; the host enforces them all, and the
/// schema reference lists the others.
fn limits() -> String {
    let mut out = String::from(HEADER);
    for limit in limits::ALL
        .iter()
        .filter(|limit| AUTHOR_LIMITS.contains(&limit.key))
    {
        out.push('\n');
        doc(
            &mut out,
            "",
            &format!("{} ({})", limit.summary, limit.unit.as_str()),
        );
        let _ = writeln!(out, "export const {} = {};", limit.key, limit.value);
    }
    out
}

fn services() -> String {
    let mut out = String::from(HEADER);
    out.push_str(
        "\nimport { group } from \"../services.js\";\n\
import type { Listener, Subscription } from \"../services.js\";\n\
import type { ServiceParamsMap as P, ServiceResultMap as R } from \"./schema.js\";\n",
    );
    let mut groups: BTreeMap<&str, Vec<&Service>> = BTreeMap::new();
    for service in SERVICES {
        let (prefix, _) = service.name.split_once('.').unwrap_or((service.name, ""));
        if !HAND_WRITTEN.contains(&prefix) {
            groups.entry(prefix).or_default().push(service);
        }
    }
    for (prefix, services) in &groups {
        let interface = format!("{}Services", pascal(prefix));
        let _ = write!(
            out,
            "\n/** The `{prefix}.*` services. */\nexport interface {interface} "
        );
        let mut tree = Tree::default();
        for service in services {
            let path = &service.name[prefix.len() + 1..];
            tree.insert(path, service);
        }
        tree.write(&mut out, prefix, "");
        out.push('\n');
        let paths: Vec<String> = services
            .iter()
            .map(|service| quote(&service.name[prefix.len() + 1..]))
            .collect();
        let _ = writeln!(
            out,
            "\n/** The `{prefix}.*` services. */\nexport const {}: {interface} = /* @__PURE__ */ group({}, [{}]);",
            prefix,
            quote(prefix),
            paths.join(", ")
        );
    }
    out
}

/// Nested method names of one namespace (`score.subscribe` →
/// `{ score: { subscribe() } }`).
#[derive(Default)]
struct Tree<'a> {
    methods: Vec<(&'a str, &'static Service)>,
    children: BTreeMap<&'a str, Tree<'a>>,
}

impl<'a> Tree<'a> {
    fn insert(&mut self, path: &'a str, service: &'static Service) {
        match path.split_once('.') {
            Some((head, rest)) => self.children.entry(head).or_default().insert(rest, service),
            None => self.methods.push((path, service)),
        }
    }

    fn write(&self, out: &mut String, prefix: &str, indent: &str) {
        let inner = format!("{indent}  ");
        out.push_str("{\n");
        for (name, child) in &self.children {
            let path = format!("{prefix}.{name}");
            doc(out, &inner, &format!("The `{path}.*` services."));
            let _ = write!(out, "{inner}readonly {name}: ");
            child.write(out, &path, &inner);
            out.push_str(";\n");
        }
        for (name, service) in &self.methods {
            method(out, &inner, name, service);
        }
        let _ = write!(out, "{indent}}}");
    }
}

fn method(out: &mut String, indent: &str, name: &str, service: &Service) {
    let mut text = format!("`{}`.", service.name);
    match service.requires {
        Requirement::None => {}
        Requirement::Permission(permission) => {
            let _ = write!(text, " Requires the `{permission}` permission.");
        }
        Requirement::Capability(capability) => {
            let _ = write!(
                text,
                " Requires the `{capability}` capability, granted by the user."
            );
        }
    }
    if service.gesture {
        text.push_str(" Call it while handling a gesture event (`activate`, `keydown`…), or it fails with `gesture_required`.");
    }
    if service.confirm {
        text.push_str(" The host asks the user to confirm first.");
    }
    let _ = write!(
        text,
        " {}: {}.",
        if service.kind == ServiceKind::Subscribe {
            "Updates"
        } else {
            "Result"
        },
        service.result
    );
    doc(out, indent, &text);
    let key = quote(service.name);
    let optional = service.params.iter().all(|field| !field.required);
    let _ = match (service.kind, service.params.is_empty()) {
        (ServiceKind::Subscribe, true) => writeln!(
            out,
            "{indent}{name}(listener: Listener<R[{key}]>): Subscription;"
        ),
        (ServiceKind::Subscribe, false) => writeln!(
            out,
            "{indent}{name}(params: P[{key}], listener: Listener<R[{key}]>): Subscription;"
        ),
        (ServiceKind::Call, true) => writeln!(out, "{indent}{name}(): Promise<R[{key}]>;"),
        (ServiceKind::Call, false) => writeln!(
            out,
            "{indent}{name}(params{}: P[{key}]): Promise<R[{key}]>;",
            if optional { "?" } else { "" }
        ),
    };
}

fn message(name: &str) -> &'static [Field] {
    HOST_MESSAGES
        .iter()
        .find(|message| message.name == name)
        .map_or(&[], |message| message.fields)
}

fn field(fields: &'static [Field], name: &str) -> &'static [&'static str] {
    fields
        .iter()
        .find(|field| field.name == name)
        .map_or(&[], |field| field.keywords())
}

/// An object type literal of `fields`, one member per line.
fn record(out: &mut String, indent: &str, fields: &[Field]) {
    if fields.is_empty() {
        out.push_str("Record<string, never>");
        return;
    }
    let inner = format!("{indent}  ");
    out.push_str("{\n");
    for field in fields {
        doc(out, &inner, field.summary);
        let _ = writeln!(
            out,
            "{inner}readonly {}{}: {};",
            field.name,
            if field.required { "" } else { "?" },
            value_type(&field.ty)
        );
    }
    let _ = write!(out, "{indent}}}");
}

fn value_type(ty: &ValueType) -> String {
    match ty {
        ValueType::Bool => "boolean".into(),
        ValueType::Text(_)
        | ValueType::Chars(_)
        | ValueType::Identifier(_)
        | ValueType::ClassList
        | ValueType::Ref
        | ValueType::RefName => "string".into(),
        ValueType::Integer { .. }
        | ValueType::Number { .. }
        | ValueType::Id
        | ValueType::NodeRef => "number".into(),
        ValueType::Keyword(words) => keywords(words),
        ValueType::Icon => "IconName".into(),
        ValueType::ImageSource => "ImageSource".into(),
        ValueType::EventSet => "readonly EventName[]".into(),
        ValueType::NumberList(_) => "readonly number[]".into(),
        ValueType::Record("<color>") => "Color".into(),
        ValueType::Record("ServiceError") => ts_name("ServiceError").into(),
        ValueType::Record(_) | ValueType::ListOf(..) => "unknown".into(),
        ValueType::Json => "JsonValue".into(),
    }
}

fn shape(out: &mut String, indent: &str, shape: &Shape) {
    match shape {
        Shape::Null => out.push_str("null"),
        Shape::Bool => out.push_str("boolean"),
        Shape::Number | Shape::Integer => out.push_str("number"),
        Shape::Text => out.push_str("string"),
        Shape::Keyword(words) => out.push_str(&keywords(words)),
        Shape::Asset => out.push_str("AssetHandle"),
        Shape::Json => out.push_str("JsonValue"),
        Shape::Nullable(inner) => {
            self::shape(out, indent, inner);
            out.push_str(" | null");
        }
        Shape::List(item) => {
            out.push_str("ReadonlyArray<");
            self::shape(out, indent, item);
            out.push('>');
        }
        Shape::Record(members) => {
            let inner = format!("{indent}  ");
            out.push_str("{\n");
            for member in *members {
                doc(out, &inner, member.summary);
                let _ = write!(out, "{inner}readonly {}: ", member.name);
                self::shape(out, &inner, &member.shape);
                out.push_str(";\n");
            }
            let _ = write!(out, "{indent}}}");
        }
        Shape::OneOf(shapes) => {
            for (index, alternative) in shapes.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                self::shape(out, indent, alternative);
            }
        }
        Shape::Named(name) => out.push_str(ts_name(name)),
    }
}

/// The TypeScript name of a schema shape. `ServiceError` is the SDK's
/// error class; the wire value it wraps is `ServiceErrorPayload`.
fn ts_name(name: &str) -> &str {
    match name {
        "ServiceError" => "ServiceErrorPayload",
        other => other,
    }
}

fn keywords(words: &[&str]) -> String {
    words
        .iter()
        .map(|word| quote(word))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn quote(text: &str) -> String {
    serde_json::Value::from(text).to_string()
}

fn pascal(name: &str) -> String {
    let mut chars = name.chars();
    chars
        .next()
        .map(|first| first.to_ascii_uppercase().to_string() + chars.as_str())
        .unwrap_or_default()
}

/// Closes a union started with `export type X =` and `  | …` lines.
fn finish(out: &mut String) {
    if out.ends_with('\n') {
        out.pop();
    }
    out.push_str(";\n");
}

/// A TSDoc comment on one line; `*/` cannot end it early.
fn doc(out: &mut String, indent: &str, text: &str) {
    if text.is_empty() {
        return;
    }
    let _ = writeln!(out, "{indent}/** {} */", text.replace("*/", "*\\/"));
}
