import { runtime } from "./runtime.js";
import type { WidgetState } from "./state.js";
import type { EventDetailMap, EventName } from "./generated/schema.js";

/** The names in scope of an expression: `for` items or component props. */
export interface Scope {
  readonly [name: string]: unknown;
}

/** An event as the VM passes it to a handler of the view table. */
export interface NodeEvent<E extends EventName = EventName> {
  /** The event name. */
  readonly type: E;
  /** The event detail, checked by the host against the schema. */
  readonly detail: EventDetailMap[E];
}

/** A template expression of the compiled view: returns the bound value. */
export type Expression = (state: WidgetState, scope: Scope) => unknown;

/** An event handler of the compiled view. */
export type Handler = (state: WidgetState, scope: Scope, event: NodeEvent) => void;

/**
 * The expression and handler table of `view.json`: entry `i` is the
 * function of expression index `i`.
 */
export type ViewTable = ReadonlyArray<Expression | Handler>;

/**
 * Registers the table of the compiled view. Call it once, while `logic.js`
 * loads; the widget CLI generates this call, so authors rarely write it.
 *
 * Calling convention (generated by the CLI from `view.ocml`):
 *
 * - an expression is `(state, scope) => value`, a handler
 *   `(state, scope, event) => void` with `event = { type, detail }`;
 * - the body binds each name in scope from `scope` (`const item =
 *   scope.item;`), and in a handler `event` to the event detail
 *   (`const event = raw.detail;`), then returns the canonical expression
 *   text;
 * - a called name is a function exported by the logic module; `t` is the
 *   SDK's {@link t} unless the module exports its own.
 *
 * The table must have exactly as many entries as `view.json` declares
 * `expressions`, or the VM refuses the bundle.
 *
 * @example
 * ```ts
 * registerView([
 *   (state) => formatTime(state.now as number),
 *   (state, scope, raw) => { const event = raw.detail; return toggle(event); },
 * ]);
 * ```
 */
export function registerView(table: ViewTable): void {
  runtime().view(table);
}
