#!/usr/bin/env python3
"""Generate the closed widget icon list from the pinned egui-lucide crate.

ADR 0001 (D12) makes every icon of the pinned `egui-lucide` release valid in
widget menus and content, and nothing else. This script reads the crate's own
name table (`NAMES` in `src/generated.rs`) so the schema matches the icons the
host can draw, and writes `crates/overcrow-widget-schema/src/icons_generated.rs`.

    python3 scripts/generate-widget-icons.py --source <egui-lucide-0.1.0 dir>
    python3 scripts/generate-widget-icons.py --source <dir> --check

The source is normally `$CARGO_HOME/registry/src/<index>/egui-lucide-0.1.0`.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

CRATE = "egui-lucide"
CRATE_VERSION = "0.1.0"
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates/overcrow-widget-schema/src/icons_generated.rs"
MAX_SOURCE_BYTES = 16 * 1024 * 1024
NAME = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


def read_source(crate_dir: Path) -> bytes:
    manifest = (crate_dir / "Cargo.toml").read_text(encoding="utf-8")
    if not re.search(rf'^name = "{CRATE}"$', manifest, re.M) or not re.search(
        rf'^version = "{re.escape(CRATE_VERSION)}"$', manifest, re.M
    ):
        fail(f"source is not {CRATE} {CRATE_VERSION}")
    source = crate_dir / "src/generated.rs"
    if source.stat().st_size > MAX_SOURCE_BYTES:
        fail("generated.rs is unexpectedly large")
    return source.read_bytes()


def parse(source: bytes) -> tuple[str, list[str]]:
    text = source.decode("utf-8")
    version = re.search(r'^pub const LUCIDE_VERSION: &str = "([0-9.]+)";$', text, re.M)
    count = re.search(r"^pub const ICON_COUNT: usize = ([0-9]+);$", text, re.M)
    table = re.search(
        r"^pub\(crate\) static NAMES: \[&str; ([0-9]+)\] = \[\n(.*?)^\];$",
        text,
        re.M | re.S,
    )
    if not (version and count and table):
        fail("unexpected generated.rs layout")
    names = []
    for line in table.group(2).splitlines():
        match = re.fullmatch(r'    r"([^"]*)",', line)
        if not match or not NAME.fullmatch(match.group(1)):
            fail("unexpected icon name entry")
        names.append(match.group(1))
    expected = int(count.group(1))
    if len(names) != expected or int(table.group(1)) != expected:
        fail("icon count mismatch")
    if len(set(names)) != len(names):
        fail("duplicate icon name")
    return version.group(1), sorted(names)


def render(source: bytes, lucide: str, names: list[str]) -> str:
    digest = hashlib.sha256(source).hexdigest()
    lines = [
        "// @generated by scripts/generate-widget-icons.py. Do not edit.",
        f"// Source: {CRATE} {CRATE_VERSION}, src/generated.rs SHA-256 {digest}.",
        "",
        f'pub const ICON_CRATE: &str = "{CRATE} {CRATE_VERSION}";',
        f'pub const LUCIDE_VERSION: &str = "{lucide}";',
        "",
        "/// Every icon name of the pinned crate, sorted for binary search.",
        f"pub static ICONS: [&str; {len(names)}] = [",
        *(f'    "{name}",' for name in names),
        "];",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", required=True, type=Path, help="egui-lucide crate directory")
    parser.add_argument("--check", action="store_true", help="compare without writing")
    arguments = parser.parse_args()
    source = read_source(arguments.source)
    lucide, names = parse(source)
    output = render(source, lucide, names)
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != output:
            fail(f"{OUTPUT.relative_to(ROOT)} is out of date")
        print("Widget icon list is up to date")
        return
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {len(names)} icons (Lucide {lucide}) to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
